# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160401070420 on 2016-05-16 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(upload_to=b''),
        ),
    ]
